
name: Check app updates

on:
  push:
    branches: [ v3-dev ]

  workflow_dispatch:
  schedule: 
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for updates
        run: |
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          git clone https://github.com/runcitadel/dev-tools
          cd dev-tools
          yarn && yarn tsc
          yarn citadel-dev appcheck -d ../apps
          cd ..
          rm -rf dev-tools
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -a -m "Update apps" || true
          git push
